"""Fixed-configuration experiment runners."""

from rpe.runner.phase1_perturbations import (
    P10MemoryAdmission,
    estimate_p10_peak_bytes,
    operator_for,
    run_perturbation_cell,
    run_shard_payload,
    run_source_cells,
)
from rpe.runner.phase1_types import (
    CellEvidence,
    CellStatus,
    PerturbedRecord,
    Phase1Cell,
    Phase1RunnerError,
    Phase1ShardPayload,
)
from rpe.runner.phase3_baseline_formal import (
    BaselineCoveragePolicy,
    BaselineCoverageResult,
    BaselineFormalError,
    BaselineFormalReceipt,
    BaselineFormalSummary,
    BaselineRunStatus,
    SystemCoverageSummary,
    build_baseline_receipt_artifact,
    evaluate_baseline_coverage,
    load_phase3_baseline_formal_config,
    load_rruff_baseline_formal_sources,
    verify_phase3_baseline_formal,
)
from rpe.runner.phase3_denoising_formal import (
    DenoisingFormalCoveragePolicy,
    DenoisingFormalError,
    DenoisingFormalFitReceipt,
    DenoisingFormalSummary,
    DenoisingFormalTransformReceipt,
    build_phase3_denoising_formal,
    evaluate_denoising_coverage,
    load_phase3_denoising_formal_config,
    load_phase3_denoising_formal_inputs,
    verify_phase3_denoising_formal,
)
from rpe.runner.phase3_peak_formal import (
    PeakFormalCoveragePolicy,
    PeakFormalError,
    PeakFormalReceipt,
    PeakFormalSummary,
    build_phase3_peak_formal,
    evaluate_peak_formal_coverage,
    load_phase3_peak_formal_config,
    load_phase3_peak_formal_sources,
    verify_phase3_peak_formal,
)
from rpe.runner.phase3_dl_audit import (
    DlAuditConfig,
    DlAuditError,
    DlAuditSummary,
    build_phase3_dl_audit,
    derive_dl_candidate_audit,
    load_phase3_dl_audit_config,
)
from rpe.runner.phase3_dl_audit_verifier import verify_phase3_dl_audit
from rpe.runner.phase4_d1_protocol_a import (
    D1ProtocolAInputs,
    Phase4D1ProtocolAConfig,
    Phase4D1ProtocolAError,
    Phase4D1ProtocolASummary,
    build_phase4_d1_protocol_a,
    load_phase4_d1_protocol_a_config,
    validate_d1_parent_authorities,
)
from rpe.runner.phase4_d1_protocol_a_verifier import (
    Phase4D1ProtocolAVerifierError,
    verify_phase4_d1_protocol_a,
)
from rpe.runner.phase4_d1_protocol_b import (
    Phase4D1ProtocolBConfig,
    Phase4D1ProtocolBError,
    Phase4D1ProtocolBSummary,
    build_phase4_d1_protocol_b,
    load_phase4_d1_protocol_b_config,
)
from rpe.runner.phase4_d1_protocol_b_verifier import (
    Phase4D1ProtocolBVerifierError,
    verify_phase4_d1_protocol_b,
)
from rpe.runner.phase4_d1_protocol_b_eligibility import (
    D1ProtocolBEligibilityInputs,
    Phase4D1ProtocolBEligibilityConfig,
    Phase4D1ProtocolBEligibilityError,
    Phase4D1ProtocolBEligibilitySummary,
    build_phase4_d1_protocol_b_eligibility,
    load_phase4_d1_protocol_b_eligibility_config,
    reconstruct_d1_protocol_b_inputs,
)
from rpe.runner.phase4_d1_protocol_b_eligibility_verifier import (
    Phase4D1ProtocolBEligibilityVerifierError,
    verify_phase4_d1_protocol_b_eligibility,
)


__all__ = [
    "Phase4D1ProtocolBConfig",
    "Phase4D1ProtocolBError",
    "Phase4D1ProtocolBSummary",
    "Phase4D1ProtocolBVerifierError",
    "build_phase4_d1_protocol_b",
    "load_phase4_d1_protocol_b_config",
    "verify_phase4_d1_protocol_b",
    "D1ProtocolBEligibilityInputs",
    "Phase4D1ProtocolBEligibilityConfig",
    "Phase4D1ProtocolBEligibilityError",
    "Phase4D1ProtocolBEligibilitySummary",
    "Phase4D1ProtocolBEligibilityVerifierError",
    "build_phase4_d1_protocol_b_eligibility",
    "load_phase4_d1_protocol_b_eligibility_config",
    "reconstruct_d1_protocol_b_inputs",
    "verify_phase4_d1_protocol_b_eligibility",
    "D1ProtocolAInputs",
    "Phase4D1ProtocolAConfig",
    "Phase4D1ProtocolAError",
    "Phase4D1ProtocolASummary",
    "Phase4D1ProtocolAVerifierError",
    "build_phase4_d1_protocol_a",
    "load_phase4_d1_protocol_a_config",
    "validate_d1_parent_authorities",
    "verify_phase4_d1_protocol_a",
    "DlAuditConfig",
    "DlAuditError",
    "DlAuditSummary",
    "build_phase3_dl_audit",
    "derive_dl_candidate_audit",
    "load_phase3_dl_audit_config",
    "verify_phase3_dl_audit",
    "PeakFormalCoveragePolicy",
    "PeakFormalError",
    "PeakFormalReceipt",
    "PeakFormalSummary",
    "build_phase3_peak_formal",
    "evaluate_peak_formal_coverage",
    "load_phase3_peak_formal_config",
    "load_phase3_peak_formal_sources",
    "verify_phase3_peak_formal",
    "DenoisingFormalCoveragePolicy",
    "DenoisingFormalError",
    "DenoisingFormalFitReceipt",
    "DenoisingFormalSummary",
    "DenoisingFormalTransformReceipt",
    "build_phase3_denoising_formal",
    "evaluate_denoising_coverage",
    "load_phase3_denoising_formal_config",
    "load_phase3_denoising_formal_inputs",
    "verify_phase3_denoising_formal",
    "BaselineCoveragePolicy",
    "BaselineCoverageResult",
    "BaselineFormalError",
    "BaselineFormalReceipt",
    "BaselineFormalSummary",
    "BaselineRunStatus",
    "SystemCoverageSummary",
    "build_baseline_receipt_artifact",
    "evaluate_baseline_coverage",
    "load_phase3_baseline_formal_config",
    "load_rruff_baseline_formal_sources",
    "verify_phase3_baseline_formal",
    "CellEvidence",
    "CellStatus",
    "P10MemoryAdmission",
    "PerturbedRecord",
    "Phase1Cell",
    "Phase1RunnerError",
    "Phase1ShardPayload",
    "estimate_p10_peak_bytes",
    "operator_for",
    "run_perturbation_cell",
    "run_shard_payload",
    "run_source_cells",
]
